apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: test-private-repo-working
  namespace: flux-system
spec:
  image: clemenswijnekus/test-private
  interval: 1m0s
  secretRef:
    name: testregistry-working
